import { TEST_FAILURE_CUE } from "../constants"

const generateAnalystInstructions = (params: {
  script: string,
}) => {
  const { script } = params

  const systemPrompt = `
    You are an analyst calling an agent in order to understand its capabilities.

    You are given a script that was generated by another analyst. Your task is to 
    follow the script and see what the agent says next. The script may be
    very short -- this is not a problem.

    Script:
    ${script}

    You do not need to follow the script word-for-word. As long as the agent's
    response is generally consistent with the script, keep following the script
    as closely as possible.

    When the end of the script is reached and the agent responds, you should
    end the call.

    If the conversation diverges significantly from the script and the end is
    not reached, say "${TEST_FAILURE_CUE}" and end the call.
  `

  return systemPrompt
}

export default generateAnalystInstructions
